// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredJikanCache(ctx context.Context) error
	DeleteSession(ctx context.Context, id string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	DeleteWatchListEntry(ctx context.Context, arg DeleteWatchListEntryParams) error
	GetAnime(ctx context.Context, id int64) (Anime, error)
	GetAnimeNeedingRelationSync(ctx context.Context) ([]GetAnimeNeedingRelationSyncRow, error)
	GetJikanCache(ctx context.Context, key string) (string, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetUpcomingSeasons(ctx context.Context, userID string) ([]GetUpcomingSeasonsRow, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserWatchList(ctx context.Context, userID string) ([]GetUserWatchListRow, error)
	GetWatchListEntry(ctx context.Context, arg GetWatchListEntryParams) (WatchListEntry, error)
	GetWatchingAnime(ctx context.Context, userID string) ([]GetWatchingAnimeRow, error)
	MarkRelationsSynced(ctx context.Context, id int64) error
	SetJikanCache(ctx context.Context, arg SetJikanCacheParams) error
	UpdateAnimeStatus(ctx context.Context, arg UpdateAnimeStatusParams) error
	UpsertAnime(ctx context.Context, arg UpsertAnimeParams) (Anime, error)
	UpsertAnimeRelation(ctx context.Context, arg UpsertAnimeRelationParams) error
	UpsertWatchListEntry(ctx context.Context, arg UpsertWatchListEntryParams) (WatchListEntry, error)
}

var _ Querier = (*Queries)(nil)
