// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	CountPendingAnimeFetchRetries(ctx context.Context) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteAnimeFetchRetry(ctx context.Context, animeID int64) error
	DeleteContinueWatchingEntry(ctx context.Context, arg DeleteContinueWatchingEntryParams) error
	DeleteExpiredJikanCache(ctx context.Context) error
	DeleteSession(ctx context.Context, id string) error
	DeleteWatchListEntry(ctx context.Context, arg DeleteWatchListEntryParams) error
	EnqueueAnimeFetchRetry(ctx context.Context, arg EnqueueAnimeFetchRetryParams) error
	GetAnime(ctx context.Context, id int64) (Anime, error)
	GetAnimeNeedingRelationSync(ctx context.Context) ([]GetAnimeNeedingRelationSyncRow, error)
	GetContinueWatchingEntries(ctx context.Context, userID string) ([]GetContinueWatchingEntriesRow, error)
	GetContinueWatchingEntry(ctx context.Context, arg GetContinueWatchingEntryParams) (ContinueWatchingEntry, error)
	GetDueAnimeFetchRetries(ctx context.Context, limit int64) ([]AnimeFetchRetry, error)
	GetJikanCache(ctx context.Context, key string) (string, error)
	GetJikanCacheStale(ctx context.Context, key string) (string, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetUpcomingSeasons(ctx context.Context, userID string) ([]GetUpcomingSeasonsRow, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserWatchList(ctx context.Context, userID string) ([]GetUserWatchListRow, error)
	GetWatchListEntry(ctx context.Context, arg GetWatchListEntryParams) (WatchListEntry, error)
	GetWatchingAnime(ctx context.Context, userID string) ([]GetWatchingAnimeRow, error)
	MarkAnimeFetchRetryFailed(ctx context.Context, arg MarkAnimeFetchRetryFailedParams) error
	MarkRelationsSynced(ctx context.Context, id int64) error
	SaveWatchProgress(ctx context.Context, arg SaveWatchProgressParams) error
	SetJikanCache(ctx context.Context, arg SetJikanCacheParams) error
	UpdateAnimeStatus(ctx context.Context, arg UpdateAnimeStatusParams) error
	UpsertAnime(ctx context.Context, arg UpsertAnimeParams) (Anime, error)
	UpsertAnimeRelation(ctx context.Context, arg UpsertAnimeRelationParams) error
	UpsertContinueWatchingEntry(ctx context.Context, arg UpsertContinueWatchingEntryParams) (ContinueWatchingEntry, error)
	UpsertWatchListEntry(ctx context.Context, arg UpsertWatchListEntryParams) (WatchListEntry, error)
}

var _ Querier = (*Queries)(nil)
